# src/main/resources/application.yml
spring:
  application:
    name: demo
  
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://to-on.kr:3306/hanyang1?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: to_on_admin
    password: BgCt9kuMws9jOivFj05UcEYpauecNa076H0oontnNrUGgG13lr
    hikari:
      connection-timeout: 30000          # 연결 타임아웃 (30초)
      maximum-pool-size: 10              # 최대 커넥션 풀 크기
      minimum-idle: 5                    # 최소 유휴 커넥션 수
      idle-timeout: 600000               # 유휴 커넥션 유지 시간 (10분)
      max-lifetime: 1800000              # 최대 커넥션 생존 시간 (30분)
      connection-test-query: SELECT 1    # 커넥션 테스트 쿼리

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        physical_naming_strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
        dialect: org.hibernate.dialect.MySQLDialect

mybatis:
  mapper-locations: mapper/*.xml

server:
  port: 4601

logging:
  level:
    org.springframework: INFO
    org.hibernate: INFO
    com.zaxxer.hikari: DEBUG
    com.example.demo: DEBUG